### ISSUE TITLE
preprocess.py报错

### ISSUE THREAD

**Issue by SCU-JJkinging** [RowitZou/topic-dialog-summ#15]
![image](https://user-images.githubusercontent.com/59439162/140048696-5595fa30-86e3-47cf-8c75-91c1080797d2.png)
请问一下在运行 preproces.py 时报的超过最大递归深度错误怎么解决呢？

**Comment by ccclll777** [comment]
我也出现了这个问题，请问怎么解决的呢

**Comment by RowitZou** [comment]
超过最大递归深度的原因，是输入的两个文本序列过长。可以规定预处理阶段抽取句子的最大数目，以及抽取句子的最大长度。

**Comment by ccclll777** [comment]
> 超过最大递归深度的原因，是输入的两个文本序列过长。可以规定预处理阶段抽取句子的最大数目，以及抽取句子的最大长度。

好的，谢谢您。我改一下perprocess.py中的参数试试。

**Comment by ccclll777** [comment]
我发现增大参数ex_max_token_num，依然会报错，但是讲ex_max_token_num设置为400之后原来发现错误的地方现在不出错了。
