### ISSUE TITLE
torch版本导致的问题

### ISSUE THREAD

**Issue by Hoogck** [RowitZou/topic-dialog-summ#16]
我环境里面torch==1.1.0，pytorch==1.8.0，pytorch-transformers==1.1.0，torchtext==0.4.0。在联合训练的时候报如下错误：
[alive_seq.index_select(0, select_indices),
RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float'
如果卸载pytorch会报torch.nn*找不到；代码里面大量使用了index_select，如果用新版的改掉的话，中间向量的维度和类型好像都有问题。请问这个怎么解决，盼复谢谢

**Comment by RowitZou** [comment]
select_indices 必须是整型，int64 数组或者是 torch.long() 类型的 tensor。

**Comment by Hoogck** [comment]
好的，感谢博主解答，这个问题昨天已经解决了
