### ISSUE TITLE
RLLOSS

### ISSUE THREAD

**Issue by lulia0228** [RowitZou/topic-dialog-summ#24]
还未深入看rl梯度策略，想请教下作者我的rlloss是否正常
![image](https://user-images.githubusercontent.com/49608151/150272089-fc866c55-cc80-4ac3-8c20-953fc901db21.png)

**Comment by RowitZou** [comment]
RL loss是正常的，正负分别代表相对于baseline更好和更差的采样结果。

**Comment by lulia0228** [comment]
ok  感谢回复~

**Comment by lulia0228** [comment]
> RL loss是正常的，正负分别代表相对于baseline更好和更差的采样结果。

感谢您的回复！
