### ISSUE TITLE
Pre-trained model for english data

### ISSUE THREAD

**Issue by san7988** [RowitZou/topic-dialog-summ#3]
Hi Team,

Great work. The paper was very nice. Thanks for sharing the code as well.

The data that we have does not have ground truths/abstract summaries. Is there any pretrained model available in english language that we can use?

Thanks in advance

**Comment by RowitZou** [comment]
Thanks for your attention to our work.

You can pre-train the model on the available English dialogue summarization benchmarks.

Here are two high-quality datasets for dialogue summarization:

https://arxiv.org/abs/1911.12237
https://arxiv.org/abs/2104.05938

**Comment by san7988** [comment]
Thanks a lot for the pointers.
