### ISSUE TITLE
求训练模型

### ISSUE THREAD

**Issue by AsphaltC** [RowitZou/topic-dialog-summ#8]
博主你好！想问一下是否能够提供已经训练好的模型呢？谢谢！

**Comment by RowitZou** [comment]
The model training and testing were conducted on the Alibaba Server when I was an intern at Alibaba. I am sorry that the trained model is not available right now. You can follow the README to conduct experiments on your own datasets.

**Comment by AsphaltC** [comment]
ok, thanks!
